import type { Metadata } from "next";
import { Noto_Sans_KR, Baloo_Bhai_2 } from "next/font/google";
import "./globals.css";
import Footer from '@/app/component/Footer';
import Navi from '@/app/component/Navi';

const notoSansKr = Noto_Sans_KR({ subsets: ["latin"] });
const balooBhai = Baloo_Bhai_2({ 
  subsets: ["latin"],
  variable: "--Baloo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${notoSansKr.className} ${balooBhai.variable}`}>
        <Navi />
        <div className="mt-16 md:mt-0">
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
