import type { Metadata } from "next";
import { Noto_Sans_KR, Baloo_Bhai_2 } from "next/font/google";
import "./globals.css";
import Navi from "./component/navi";

const notoSansKr = Noto_Sans_KR({ subsets: ["latin"] });
const balooBhai = Baloo_Bhai_2({ 
  subsets: ["latin"],
  variable: "--Baloo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKr.className} ${balooBhai.variable}`}>
        <Navi />
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
