import type {Metadata} from 'next';
import {Baloo_Bhai_2, Noto_Sans_KR} from 'next/font/google';
import './globals.css';
import Footer from '@/app/component/Footer';
import Navi from '@/app/component/Navi';
import {Suspense} from 'react';


const notoSansKr = Noto_Sans_KR({subsets: ['latin']});
const balooBhai = Baloo_Bhai_2({
    subsets: ['latin'],
    variable: '--Baloo',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
        <body className={`${notoSansKr.className} ${balooBhai.variable}`}>
        <Suspense><Navi/></Suspense>
        <div className="mt-16">
            {children}
            <Suspense><Footer/></Suspense>
        </div>
        </body>
        </html>
    );
}
